# 13.1 Fitting a Line

I want to train a model that represents a linear relationship 

between the feature and target vector.

In [13]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston

# Load data with only two features
boston = load_boston()
features = boston.data[:, 0:2]
target = boston.target
pd.DataFrame(features)

# Create linear regression
regression = LinearRegression()

# Fit the linear regression
model = regression.fit(features, target)
model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

y = a0 + a1・x1 + a2・x2 + e

- y: target

- xi: data for a single feature

- a0: bias or intercept

- a1 and a2: coefficients

- e: error

In [14]:
# View the intercept
model.intercept_

22.485628113468223

In [15]:
# View the feature coefficients 
model.coef_

array([-0.35207832,  0.11610909])

In [16]:
# First value in the target vector multiplied by 1000
target[0]*1000

24000.0

In [17]:
# Predict the target value of the first observation, multiplied by 1000
model.predict(features)[0]*1000

24573.366631705547

In [19]:
# First coefficient multiplied by 1000
model.coef_[0]*1000

-352.07831564026765

# 13.2 Handling Interactive Effects

I have a feature whose effect on the target variable depends on another feature.

Solution: Create an interaction term to capture the dependence.

In [21]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
from sklearn.preprocessing import PolynomialFeatures

# Load data with onpy two features
boston = load_boston()
features = boston.data[:, 0:2]
target = boston.target

# Create interaction term
interaction = PolynomialFeatures(degree=3, include_bias=False,
                                 interaction_only=True)

features_interaction = interaction.fit_transform(features)

# Create linear regression
regression = LinearRegression()

# Fit the linear regression
model = regression.fit(features_interaction, target)

y = a0 + a1・x1 + a2・x2 + a3・x1・x2 + e

- y: target

- xi: data for a single feature

- x1・x2: interaction between x1 and x2

- a0: bias or intercept

- a1 and a2: coefficients

- e: error

In [22]:
# View the feature values for first observation
features[0]

array([6.32e-03, 1.80e+01])

In [26]:
import numpy as np

# For each observation, multiply the values of the first and second feature
interaction_term = np.multiply(features[:, 0], features[:, 1])
interaction_term[0]

0.11376

In [27]:
# View the values of the first ibservation
features_interaction[0]

array([6.3200e-03, 1.8000e+01, 1.1376e-01])

# 13.3 Fitting a Nonlinear Relationship

I want to model a nonlinear relationship.

In [36]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
from sklearn.preprocessing import PolynomialFeatures

# Load data with only two features
boston = load_boston()
features = boston.data[:, 0:1]
target = boston.target

# Create polynomial features x^2 and x^3
polynomial = PolynomialFeatures(degree=3, include_bias=False)
features_polynomial = polynomial.fit_transform(features)

# Create linear regression
regression = LinearRegression()

# Fit the linear regression
model = regression.fit(features_polynomial, target)

In [39]:
# View first observation
features[0]

array([0.00632])

In [40]:
# View first observation raised to the second power, x^2
features[0]**2

array([3.99424e-05])

In [42]:
# View first observation raised to the third power, x^3
features[0]**3

array([2.52435968e-07])

In [44]:
# View first observation's values for x, x^2 and x^3
features_polynomial[0]

array([6.32000000e-03, 3.99424000e-05, 2.52435968e-07])

# 13.4 Reducing Variance with Regularization

I want to reduce the variance of my linear regression model.

In [50]:
from sklearn.linear_model import Ridge
from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler

# Load data with only two features
boston = load_boston()
features = boston.data[:, 0:1]
target = boston.target

# Standardize features
scaler = StandardScaler()
features_stanardized = scaler.fit_transform(features)

# Create ridge regression with an alpha value
regression = Ridge(alpha=0.5)

# Fit the linear regression
model = regression.fit(features_stanardized, target)

RidgeCV method allows up to select the ideal value for alpha:

In [55]:
from sklearn.linear_model import RidgeCV

# Create ridge regression with three alpha values
regr_cv = RidgeCV(alphas=[0.1, 1.0, 10.0])

# Fit the linear regression 
model_cv = regr_cv.fit(features_stanardized, target)
# View coefficients
model_cv.coef_

array([-3.49860484])

In [56]:
# View alpha
model_cv.alpha_

10.0

# 13.5 Reading Features with Lasso Regression

I want to simplify my linear regression model by reducing the number of features.

In [57]:
from sklearn.linear_model import Lasso
from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler

# Load data with only two features
boston = load_boston()
features = boston.data[:, 0:1]
target = boston.target

# Standardize features
scaler = StandardScaler()
features_stanardized = scaler.fit_transform(features)

# Create lasso regression with alpha value
regression = Lasso(alpha=0.5)

# Fit the linear regression
model = regression.fit(features_stanardized, target)

In [58]:
# View coefficient
model.coef_

array([-3.06774723])

In [59]:
# Create lasso regression with a high alpha
regression = Lasso(alpha=10)

# Fit the linear regression
model_a10 = regression.fit(features_stanardized, target)
model_a10.coef_

array([-0.])