# 1.1 Creating a Vector

In [8]:
# Load library
import numpy as np
# Create a vector as a row 
vector_row = np.array([1, 2, 3])
# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])

# 1.2 Creating a Matrix

In [13]:
import numpy as np
# Create a matrix ( two-dimensional array )
matrix = np.array([[1, 2],
                 [1, 2],
                 [1, 2]])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

# 1.3 Creating a Sparse Matrix 

In [15]:
import numpy as np
from scipy import sparse
# Create a matrix
matrix = np.array([[0, 0],
                  [0, 1],
                  [3, 0]])
# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)
matrix_sparse

<3x2 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [16]:
# View sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [20]:
# Create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                        [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)
# View original sparse matrix
print(matrix_sparse)
print()
# View larger sparse matrix
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3

  (1, 1)	1
  (2, 0)	3


# 1.4 Selecting Elements

In [24]:
import numpy as np
# Create a row vector
vector = np.array([1, 2, 3, 4, 5, 6])
# Create matrix
matrix = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
# Select third element of vector
print(vector[2])
print()
# Select second row, second column
print(matrix[1,1])

3

5


In [25]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [26]:
# Select everthing up to and including the third element
vector[:3]

array([1, 2, 3])

In [27]:
# Select everything after the third element
vector[3:]

array([4, 5, 6])

In [28]:
# Select the last element
vector[-1]

6

In [29]:
# Select the first two rows and all columns of a matrix
matrix[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
# Select all rows and the second column
matrix[:, 1:2]

array([[2],
       [5],
       [8]])

# 1.5 Describing a Matrix

In [33]:
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
# View number of rows and columns
print(matrix.shape)
# View number of elements ( rows * columns )
print(matrix.size)
# View number of dimensions
print(matrix.ndim)

(3, 4)
12
2


# 1.6 Applying Operations to Elements

Apply some function to multiple elements in an array.

In [34]:
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
# Create function that adds 100 to something
add_100 = lambda i: i + 100
# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)
# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [36]:
# Much simplier method ( Add 100 to all elements )
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

# 1.7 Finding the Maximum and Minimum Values

In [37]:
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
# Return maximum element
print(np.max(matrix))
# Return minimum element
print(np.min(matrix))

9
1


In [38]:
# Find maximum element in each column
print(np.max(matrix, axis=0))
# Find maximum element in each row
print(np.max(matrix, axis=1))

[7 8 9]
[3 6 9]


# 1.8 Calculating the Average, Variance and Standard Deviation

In [40]:
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
# Return mean
print(np.mean(matrix))
# Return variance
print(np.var(matrix))
# Return standard deviation
print(np.std(matrix))
# Find the mean value in each column
print(np.mean(matrix, axis=0))

5.0
6.666666666666667
2.581988897471611
[4. 5. 6.]


# 1.9 Reshaping Arrays

Want to change the shape ( number of rows and columns ) of an array without changing the element values.

In [41]:
import numpy as np
# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                [10, 11, 12]])
# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [42]:
matrix.reshape(1, -1)
# -1 means 'as many columns as needed'

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [43]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# 1.10 Transposing a Vector or Matrix

In [49]:
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
# Transpose matrix
print(matrix.T)
print()
# Transpose vector
print(np.array([1, 2, 3, 4, 5, 6]).T)
print()
# Tranpose row vector
print(np.array([[1, 2, 3, 4, 5, 6]]).T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[1 2 3 4 5 6]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


# 1.11 Flattening a Matrix

Transforming a matrix into a one-dimensional  array.

In [50]:
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
# Flatten matrix
print(matrix.flatten())
# Matrix reshape
matrix.reshape(1, -1)

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# 1.12 Finding the Rank of a Matrix

In [54]:
import numpy as np
# Create matrix
matrix = np.array([[1, 1, 1],
                 [1, 1, 10],
                 [1, 1, 15]])

print(np.linalg.matrix_rank(matrix))
print()
matrix2 = np.array([[1, 1, 1, 1],
                 [1, 1, 10, 11],
                 [1, 1, 15, 1]])
# Return matrix rank (縱)
print(np.linalg.matrix_rank(matrix2))

2

3


# 1.13 Calculating the Determinant

In [56]:
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
# Return determinant of matrix
np.linalg.det(matrix)

-9.51619735392994e-16

# 1.14 Getting the Diagonal of a Matrix 

In [59]:
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])
# Return diagonal elements
print(matrix.diagonal())
print()
# Return diagonal one above the main diagonal
print(matrix.diagonal(offset=1))
print()
# Return diagonal one below the main diagonal
print(matrix.diagonal(offset=-1))

[1 4 9]

[2 6]

[2 8]


# 1.15 Calculating the Trace of a Matrix

sum(diagonal)

In [61]:
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])
# Return trace
matrix.trace()

# or : sum(matrix.diagonal())

14

# 1.16 Finding Eigenvalues and Eigenvectors 

In [66]:
import numpy as np
# Create matrix
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
# View eignevalues
print(eigenvalues)
print()
# View eignevectors
print(eigenvectors)

[13.55075847  0.74003145 -3.29078992]

[[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


# 1.17 Calculating Dot Products 

In [67]:
import numpy as np
# Create two vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
# Calculate dot product
np.dot(vector_a, vector_b)

32

# 1.18 Adding and Subtracting Matrices

In [68]:
import numpy as np
# Create matrix
matrix_a = np.array([[1, 1, 1],
                    [1, 1, 1],
                    [1, 1, 2]])
# Create matrix
matrix_b = np.array([[1, 3, 1],
                    [1, 3, 1],
                    [1, 3, 8]])
# Add two matrices
print(np.add(matrix_a, matrix_b))
print()
# Subtract two matrices
print(np.subtract(matrix_a, matrix_b))

[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]

[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]


# 1.19 Multiplying Matrices

In [69]:
import numpy as np
# Create matrix
matrix_a = np.array([[1, 1],
                     [1, 2]])
# Create matrix
matrix_b = np.array([[1, 3],
                     [1, 2]])
# Multiply two matrices
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

# 1.20 Inverting a Matrix

In [73]:
import numpy as np
# Create matrix
matrix = np.array([[1, 4],
                   [2, 5]])
# Calculate inverse of matrix
print(np.linalg.inv(matrix))
print()
# Multiplying matrix and its inverse
matrix @ np.linalg.inv(matrix)

[[-1.66666667  1.33333333]
 [ 0.66666667 -0.33333333]]



array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

# 1.21 Generating Random Values

In [79]:
import numpy as np
# Set seed
np.random.seed(0)
# Generate thress random floats between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [80]:
# Generate thress random integers between 1 and 10
np.random.randint(0, 11, 3)

array([3, 7, 9])

In [81]:
# Draw three numbers from a normal distribution with mean 0.0 and std of 1.0
np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [83]:
# Draw three numbers from a logistic distribution with mean 0.0 
# and scale of 1.0
np.random.logistic(0.0, 1.0, 3)

array([-0.98118713, -0.08939902,  1.46416405])

In [84]:
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.47997717, 1.3927848 , 1.83607876])