# 4.1 Rescaling Feature

In [2]:
import numpy as np
from sklearn import preprocessing
# Create feature
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
# Create scaler
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1))
# Scale feature
scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

# 4.2 Standardizing a Feature

In [8]:
import numpy as np
from sklearn import preprocessing
# Create feature
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
# Create scaler
scaler = preprocessing.StandardScaler()
# Transform the feature
standardized = scaler.fit_transform(x)
print(standardized)
print()
# Print mean and std
print('mean: ', round(standardized.mean()))
print('std:', round(standardized.std()))

[[-0.76058269]
 [-0.54177196]
 [-0.35009716]
 [-0.32271504]
 [ 1.97516685]]

mean:  0.0
std: 1.0


Data has significant outliers.

In [9]:
# Create feature
robust_scaler = preprocessing.RobustScaler()
# Transform feature
robust_scaler.fit_transform(x)

array([[-1.87387612],
       [-0.875     ],
       [ 0.        ],
       [ 0.125     ],
       [10.61488511]])

# 4.3 normalizing Observations

Want to rescale the feature values of observations to have unit norm.
- unit norm : a total length of 1

In [10]:
import numpy as np
from sklearn.preprocessing import Normalizer
# Create feature
features = np.array([[0.5, 0.5], [1.1, 3.4], [1.5, 20.2],
                     [1.63, 34.4],[10.9, 3.3]])
# Create normalizer
  # l2: Euclidean norm
normalizer = Normalizer(norm='l2')
# Transform feature matrix
normalizer.transform(features)

array([[0.70710678, 0.70710678],
       [0.30782029, 0.95144452],
       [0.07405353, 0.99725427],
       [0.04733062, 0.99887928],
       [0.95709822, 0.28976368]])

Euclidean norm(l2)

In [11]:
# Transform feature matrix
feature_l2_norm = Normalizer(norm='l2').transform(features)
feature_l2_norm

array([[0.70710678, 0.70710678],
       [0.30782029, 0.95144452],
       [0.07405353, 0.99725427],
       [0.04733062, 0.99887928],
       [0.95709822, 0.28976368]])

Manhattan norm(l1)

In [12]:
feature_l1_norm = Normalizer(norm='l1').transform(features)
feature_l1_norm

array([[0.5       , 0.5       ],
       [0.24444444, 0.75555556],
       [0.06912442, 0.93087558],
       [0.04524008, 0.95475992],
       [0.76760563, 0.23239437]])

In [14]:
# Print sum
print('Sum of the first observation\'s value:', 
      feature_l1_norm[0, 0] + feature_l1_norm[0, 1])

Sum of the first observation's value: 1.0


# 4.4 Generating Polynomial and Interaction Features

In [17]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
# Create feature matrix
features = np.array([[2, 3], [2, 3], [2, 3]])
# Create PolynomialFeatures object
polynomial_interaction = PolynomialFeatures(degree=2, include_bias=False)
# Create polynomial features
polynomial_interaction.fit_transform(features)

array([[2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.]])

In [18]:
interaction = PolynomialFeatures(degree=2, interaction_only=True,
                                include_bias=False)
interaction.fit_transform(features)

array([[2., 3., 6.],
       [2., 3., 6.],
       [2., 3., 6.]])

# 4.5 Transforming Features

Use ' FunctionTransformer ' to apply a function to a set of features:

In [19]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer
# Create feature matrix
features = np.array([[2, 3], [2, 3], [2, 3]])
# Define a simple function
def add_ten(x):
    return x + 10
# Create transformer
ten_transformer = FunctionTransformer(add_ten)
# Transform feature matrix
ten_transformer.transform(features)

array([[12, 13],
       [12, 13],
       [12, 13]])

Use ' Pandas' to apply a function to a set of features:

In [21]:
import pandas as pd
# Create DataFrame
df = pd.DataFrame(features, columns=['feature_1', 'feature_2'])
# Apply function
df.apply(add_ten)

feature_1  feature_2
0         12         13
1         12         13
2         12         13

# 4.6 Detecting Outliers

In [23]:
import numpy as np
from sklearn.covariance import EllipticEnvelope
from sklearn.datasets import make_blobs
# Create simulated data
features, _ = make_blobs(n_samples=10, n_features=2,
                        centers=1, random_state=1)
# Replace the first observation's values with extreme values
features[0,0]=10000
features[0,1]=10000
# Create detector
outlier_detector = EllipticEnvelope(contamination=.1)
# Fit detector
outlier_detector.fit(features)
# Predict Ouliers
outlier_detector.predict(features)

array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

Using interquartile range ( IQR ):

In [25]:
# Create feature
feature = features[:,0]
# Create a function to return index of outliers
def indicies_of_outliers(x):
    q1, q3 = np.percentile(x, [25, 75])
    iqr = q3 - q1
    lower_bound = q1 - (iqr * 1.5)
    upper_bound = q3 + (iqr * 1.5)
    return np.where((x > upper_bound) | (x<lower_bound))
# Run function
indicies_of_outliers(feature)

(array([0]),)

# 4.7 Handling outliers

Strategy1 : Drop the outliers

In [26]:
import pandas as pd
# Create DataFrame
houses = pd.DataFrame()
houses['Price'] = [534433, 392333, 293222, 4322032]
houses['Bathrooms'] = [2, 3.5, 2, 116]
houses['Square_Feet'] = [1500, 2500, 1500, 48000]
# Filter observations
houses[houses['Bathrooms'] < 20]

Price  Bathrooms  Square_Feet
0  534433        2.0         1500
1  392333        3.5         2500
2  293222        2.0         1500

Strategy2 : Mark them as outliers and include it as a feature

In [27]:
import numpy as np
# Create feature based on boolean condition
houses['Outlier'] = np.where(houses['Bathrooms'] < 20, 0, 1)
houses

Price  Bathrooms  Square_Feet  Outlier
0   534433        2.0         1500        0
1   392333        3.5         2500        0
2   293222        2.0         1500        0
3  4322032      116.0        48000        1

Strategy3 : Transform the feature to dampen the effect of the outlier

In [28]:
# Log feature
houses['Log_of_Square_Feet'] = [np.log(x) for x in houses['Square_Feet']]
houses

Price  Bathrooms  Square_Feet  Outlier  Log_of_Square_Feet
0   534433        2.0         1500        0            7.313220
1   392333        3.5         2500        0            7.824046
2   293222        2.0         1500        0            7.313220
3  4322032      116.0        48000        1           10.778956

# 4.8 Discretizating Features

Having a numerical feature and want to break it up into discrete bins.

First : Binarizing the feature according to some threshold

In [29]:
import numpy as np
from sklearn.preprocessing import Binarizer
# Create feature
age = np.array([[6], [12], [20], [36], [65]])
# Create binarizer
binarizer = Binarizer(18)
# Transform feature
binarizer.fit_transform(age)

array([[0],
       [0],
       [1],
       [1],
       [1]])

Second : Breaking numerical features according to multiple thresholds

In [30]:
# Bin feature
np.digitize(age, bins=[20,30,64])

array([[0],
       [0],
       [1],
       [2],
       [3]])

Third : ' 20 '

In [31]:
# Bin feature
np.digitize(age, bins=[20,30,64], right=True)

array([[0],
       [0],
       [0],
       [2],
       [3]])

Simple method

In [36]:
np.digitize(age, bins=[18])

array([[0],
       [0],
       [1],
       [1],
       [1]])

# 4.9 Grouping Observations Using Clustering

Having ' k ' groups, can use k-means clustering to group similar observations.

In [37]:
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
# Make simulated feature matrix
features, _ = make_blobs(n_samples=50, n_features=2,
                        centers=3, random_state=1)
# Create DataFrame
dataframe = pd.DataFrame(features, columns=['feature_1', 'feature_2'])
# Make k-means clusterer
clusterer = KMeans(3, random_state=0)
# Fit clusterer
clusterer.fit(features)
# Predict values
dataframe['group'] = clusterer.predict(features)
dataframe.head()

feature_1  feature_2  group
0  -9.877554  -3.336145      0
1  -7.287210  -8.353986      2
2  -6.943061  -7.023744      2
3  -7.440167  -8.791959      2
4  -6.641388  -8.075888      2

# 4.10 Deleting Observatios with Missing Values

Using numpy

In [38]:
import numpy as np
# Create feature matrix
features = np.array([[1.1, 11.1], [2.2, 22.2], 
                     [3.3, 33.3], [4.4, 44.4],
                     [np.nan, 55]])
# Keep only observations that are not (denoted by~) missing
features[~np.isnan(features).any(axis=1)]

array([[ 1.1, 11.1],
       [ 2.2, 22.2],
       [ 3.3, 33.3],
       [ 4.4, 44.4]])

Using pandas

In [44]:
import pandas as pd
# Load data
dataframe = pd.DataFrame(features, columns=['feature_1', 'feature_2'])
# Remove observations with missing values
dataframe.dropna()

feature_1  feature_2
0        1.1       11.1
1        2.2       22.2
2        3.3       33.3
3        4.4       44.4

# 4.11 Imputing Missing Values

Having a small amount of data, predict the missing values using KNN.

In [50]:
import numpy as np
from fancyimpute import KNN
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_blobs
# Make a simulated feature matrix
features, _ = make_blobs(n_samples=1000, n_features=2, random_state=1)
# Standardize the features
scaler = StandardScaler()
standardized_features = scaler.fit_transform(features)
# Replace the first feature's first value with a missing value
true_value = standardized_features[0,0]
standardized_features[0,0] = np.nan
# Predict the missing values in the feature matrix
features_knn_imputed = KNN(k=5, verbose=0).complete(standardized_features)
# Compare true and imputed values
print('True Value: ', true_value)
print('Imputed Value: ',features_knn_imputed)

AttributeError: 'KNN' object has no attribute 'complete'

Using sklearn

In [53]:
from sklearn.preprocessing import Imputer
# Create imputer
mean_imputer = Imputer(strategy='mean', axis=0)
# Impute values
features_mean_imputed = mean_imputer.fit_transform(features)
# Compare true and imputed values
print('True Value: ', true_value)
print('Imputed Value: ',features_mean_imputed[0,0])

True Value:  0.8730186113995938
Imputed Value:  -3.058372724614996
